ALTER TABLE NHANVIEN
DROP CONSTRAINT FK_NV_CSYT;

ALTER TABLE NHANVIEN
DROP CONSTRAINT FK_NV_KHOA;

ALTER TABLE BENHNHAN
DROP CONSTRAINT FK_BN_CSYT;

ALTER TABLE HSBA
DROP CONSTRAINT FK_HSBA_BN;

ALTER TABLE HSBA
DROP CONSTRAINT FK_HSBA_BS;

ALTER TABLE HSBA
DROP CONSTRAINT FK_HSBA_KHOA;

ALTER TABLE HSBA
DROP CONSTRAINT FK_HSBA_CSYT;

ALTER TABLE HSBA_DV
DROP CONSTRAINT FK_HSBADV_HSBA;

ALTER TABLE HSBA_DV
DROP CONSTRAINT FK_HSBADV_DV;

ALTER TABLE HSBA_DV
DROP CONSTRAINT FK_HSBADV_KTV;

DROP TABLE CSYT;
DROP TABLE KHOA;
DROP TABLE DICHVU;
DROP TABLE NHANVIEN;
DROP TABLE BENHNHAN;
DROP TABLE HSBA;
DROP TABLE HSBA_DV;

CREATE TABLE CSYT
(
    MA_CSYT CHAR(4),
    TEN_CSYT VARCHAR2(30) NOT NULL,
    DC_CSYT VARCHAR2(80) NOT NULL,
    SDT_CSYT CHAR(10) NOT NULL,
    CONSTRAINT PK_CSYT PRIMARY KEY(MA_CSYT)
);

CREATE TABLE KHOA
(
    MA_KHOA CHAR(4),
    TEN_KHOA VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_KHOA PRIMARY KEY(MA_KHOA)
);

CREATE TABLE DICHVU
(
    MA_DV CHAR(4),
    TEN_DV CHAR(4) NOT NULL,
    GHICHU VARCHAR2(100),
    CONSTRAINT PK_DV PRIMARY KEY(MA_DV)
);

CREATE TABLE NHANVIEN
(
    MA_NV CHAR(6),
    HOTEN VARCHAR2(30) NOT NULL,
    PHAI  VARCHAR2(3) NOT NULL,
    NGAYSINH DATE NOT NULL,
    CMND CHAR(10) NOT NULL UNIQUE,
    QUEQUAN VARCHAR2(20) NOT NULL,
    SDT CHAR(10) NOT NULL,
    CSYT CHAR(4),
    VAITRO VARCHAR2(20) NOT NULL,
    CHUYENKHOA CHAR(4),
    CONSTRAINT PK_NV PRIMARY KEY(MA_NV),
    CONSTRAINT CONS_PHAI CHECK (PHAI IN ('Nam','Nữ')),
    CONSTRAINT CONS_VAITRO CHECK (VAITRO IN ('Thanh tra', 'Cơ sở y tế', 'Y sĩ/Bác sĩ', 'Nghiên cứu'))
);

CREATE TABLE BENHNHAN
(
    MA_BN CHAR(7),
    MA_CSYT CHAR(4) NOT NULL,
    TEN_BN VARCHAR2(30) NOT NULL,
    CMND CHAR(10) NOT NULL UNIQUE,
    NGAYSINH DATE NOT NULL,
    SONHA VARCHAR(10) NOT NULL,
    TENDUONG VARCHAR2(30) NOT NULL,
    QUANHUYEN VARCHAR2(30) NOT NULL,
    TINHTP VARCHAR2(30) NOT NULL,
    TIENSUBENH VARCHAR2(250),
    TIENSUBENHGD VARCHAR2(250),
    DIUNGTHUOC VARCHAR2(250),
    CONSTRAINT PK_BN PRIMARY KEY(MA_BN)
);

CREATE TABLE HSBA
(
    MA_HSBA CHAR(7),
    MA_BN CHAR(7) NOT NULL,
    NGAY DATE NOT NULL,
    CHUANDOAN VARCHAR2(250) NOT NULL,
    MA_BS CHAR(5) NOT NULL,
    MA_KHOA CHAR(4) NOT NULL,
    MA_CSYT CHAR(4) NOT NULL,
    KETLUAN VARCHAR2(250) NOT NULL,
    CONSTRAINT PK_HSBA PRIMARY KEY(MA_HSBA)
);

CREATE TABLE HSBA_DV
(
    MA_HSBA CHAR(7),
    MA_DV CHAR(4),
    NGAY DATE,
    MA_KTV CHAR(5) NOT NULL,
    KETQUA VARCHAR2(250) NOT NULL,
    CONSTRAINT PK_HSBA_DV PRIMARY KEY(MA_HSBA, MA_DV, NGAY)
);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_CSYT
FOREIGN KEY(CSYT)
REFERENCES CSYT;

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_KHOA
FOREIGN KEY(CHUYENKHOA)
REFERENCES KHOA;

ALTER TABLE BENHNHAN
ADD CONSTRAINT FK_BN_CSYT
FOREIGN KEY(MA_CSYT)
REFERENCES CSYT;

ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_BN
FOREIGN KEY(MA_BN)
REFERENCES BENHNHAN;

ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_BS
FOREIGN KEY(MA_BS)
REFERENCES NHANVIEN;

ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_KHOA
FOREIGN KEY(MA_KHOA)
REFERENCES KHOA;

ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_CSYT
FOREIGN KEY(MA_CSYT)
REFERENCES CSYT;

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBADV_HSBA
FOREIGN KEY(MA_HSBA)
REFERENCES HSBA;

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBADV_DV
FOREIGN KEY(MA_DV)
REFERENCES DICHVU;

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBADV_KTV
FOREIGN KEY(MA_KTV)
REFERENCES NHANVIEN;
